// ============================================================
// gdpr.com.tr — bilingual data + UI strings
// ============================================================

// ----- UI i18n strings -----
window.I18N = {
  tr: {
    brandSub: "Bilgi Merkezi",
    navAtlas: "Atlas", navGdpr: "GDPR", navCompare: "Karşılaştır", navCountries: "Ülkeler", navPrinciples: "İlkeler", navAbout: "Hakkında",
    heroEyebrow: "KVKK · GDPR · EEA",
    heroTitle: "Veri Mahremiyetinin <em>Atlası</em>",
    heroLead: "Türkiye'den Avrupa Birliği'ne, kişisel verilerin korunmasına dair yetkili otoriteler, idari para cezaları ve örnek kararlar — tek bir küre üzerinde. Bir ülkeyi seçin, o ülkeye özgü çerçeveyi keşfedin.",
    heroCta: "Aşağıdaki küreden bir ülke seçin",
    globeLabel: "— Atlas Mundi Privaticus —",
    globeLoading: "Küre yükleniyor…",
    globeStat: "yetki alanı",
    gdprEyebrow: "Çatı Çerçeve",
    gdprTitle: "Genel Veri Koruma <em>Tüzüğü</em>",
    gdprDesc: "25 Mayıs 2018'de yürürlüğe giren (EU) 2016/679 sayılı GDPR, AB'nin 27 üye devleti ve 3 EEA ülkesinde doğrudan uygulanır. Hesap verebilirlik, veri koruma etki değerlendirmesi, 72 saatlik ihlal bildirimi ve yurt dışı aktarımda yeterlilik rejimi temel sütunlardır.",
    gdprLink: "EUR-Lex'te tam metin ↗",
    gdprStatYear: "Yürürlük",
    gdprStatCountries: "AB + EEA",
    gdprStatFine: "veya cironun %4'ü",
    gdprStatArticles: "madde",
    countriesTitle: "Listeden Seçin",
    countriesSub: "Türkiye, AB üyeleri ve EEA — toplam 31 yetki alanı",
    searchPlaceholder: "Ülke ara…",
    principlesEyebrow: "Temel Sütunlar",
    principlesTitle: "Üç İlke",
    principlesSub: "KVKK ve GDPR ekosisteminin çakıştığı ve ayrıldığı üç ana eksen.",
    p1Title: "Veri Sahibi Hakları",
    p1Body: "Erişim, düzeltme, silme, taşınabilirlik, itiraz ve otomatik karara karşı çıkma hakları. KVKK ve GDPR büyük ölçüde örtüşür; Almanya, Fransa, İspanya gibi ülkelerde dijital miras ve çalışan verisi gibi alanlarda yerel ek hükümler bulunur.",
    p2Title: "Yurt Dışı Aktarım",
    p2Body: "GDPR ekosistemi yeterlilik kararları, Standart Sözleşme Maddeleri (SCC) ve Bağlayıcı Şirket Kuralları (BCR) üzerinden işler. Türkiye, Mart 2024 değişikliğiyle benzer bir SCC rejimini benimsemiştir; öncesinde Kurul izni şarttı.",
    p3Title: "İdari Para Cezaları",
    p3Body: "GDPR azami cezası 20 milyon EUR veya küresel cironun %4'üdür. Türkiye'de 1 Ocak 2026 itibarıyla en yüksek tek başlık 17,09 milyon TL'dir (2025'te 13,62 milyon TL idi). Tek bir ihlal birden çok yaptırıma yol açabilir.",
    footerHubTitle: "gdpr.com.tr Bilgi Merkezi",
    footerHubDesc: "KVKK ve GDPR dünyasını paylaşan profesyoneller için hazırlanmış bağımsız bir bilgi haritası. İçerikler Kurul kararları, EDPB rehberleri ve ulusal DPA güncellemeleriyle yenilenir.",
    footerDisclaimer: "Bu sitedeki içerikler genel bilgilendirme amaçlıdır ve hukuki tavsiye niteliği taşımaz. Somut bir mesele için uzman görüşü alınmalıdır.",
    footerResources: "Kaynaklar",
    footerContact: "İletişim",
    footerLocation: "Türkiye, İstanbul",
    footerCopyright: "© 2026 gdpr.com.tr — tüm hakları saklıdır.",
    footerTagline: "Bağımsız bilgi merkezi · Hukuki danışmanlık değildir",
    // Side-panel labels
    pnlRegulator: "Düzenleyici Otorite",
    pnlMaxFine: "Azami İdari Para Cezası",
    pnlRights: "Veri Sahibi Hakları",
    pnlBases: "Hukuki Sebepler",
    pnlExtraterritorial: "Ülke Dışı Uygulama",
    pnlNotable: "Öne Çıkan Kararlar",
    pnlSource: "Resmi Kaynak",
    pnlYear: "Yürürlük",
    // Default GDPR field values
    defGdprRights: ["Erişim","Düzeltme","Silme (unutulma)","İşlemenin kısıtlanması","Veri taşınabilirliği","İtiraz","Otomatik karara itiraz"],
    defGdprBases: ["Rıza","Sözleşme","Hukuki yükümlülük","Hayati menfaat","Kamu yararı","Meşru menfaat"],
    defGdprMaxFine: "20 milyon EUR veya küresel yıllık cironun %4'ü (hangisi yüksekse).",
    defGdprExtra: "GDPR Md. 3 uyarınca AB'deki kişileri hedefleyen veya davranışlarını izleyen yurt dışı veri sorumlularını da kapsar.",
    // Dashboard v2
    dashListTitle: "Ülkeler",
    dashCompareTitle: "Karşılaştır",
    compareShowTable: "Tabloyu Aç",
    cardEmptyTitle: "Bir ülke seçin",
    cardEmptyBody: "Küreden tıklayın veya soldaki listeden bir ülke seçin. Yetkili otorite, ceza üst sınırı ve örnek kararlar burada görünecek.",
    compareEmptyDash: "Karşılaştırma tablosu için en az iki ülke seçin.",
    filterAll: "Hepsi",
    filterGdpr: "GDPR",
    filterEea: "EEA",
    globeHint: "Sürükle · küreyi döndür · ülkeye tıkla",
    listEmpty: "Sonuç bulunamadı.",
    slotAdd: "Ülke ekle",
    // Compare section
    compareEyebrow: "Yan Yana",
    compareTitle: "Karşılaştır",
    compareSub: "En fazla dört ülkeyi seçin; çerçeve, otorite, ceza ve yaptırım kararlarını yan yana inceleyin.",
    compareEmpty: "Karşılaştırmak için yukarıdaki \"+ Ülke Ekle\" kutularından seçim yapın.",
    compareClear: "Hepsini temizle",
    compareHint: "Bir ülke daha ekleyin — karşılaştırma 2 ülkeden itibaren açılır.",
    compareSlotEmpty: "Ülke ekle",
    pickerTitle: "Ülke seçin",
    pickerEmpty: "Sonuç bulunamadı.",
    pnlAddCompare: "Karşılaştırmaya ekle",
    pnlAddedCompare: "Karşılaştırmaya eklendi",
    pnlFullCompare: "Karşılaştırma dolu (4 ülke)",
    // Compare table row labels
    cmpFramework: "Çerçeve",
    cmpYear: "Yürürlük",
    cmpLawTitle: "Düzenleyici Kanun",
    cmpRegulator: "Düzenleyici Otorite",
    cmpMaxFine: "Azami Para Cezası",
    cmpRights: "Veri Sahibi Hakları",
    cmpBases: "Hukuki Sebepler",
    cmpExtraterritorial: "Ülke Dışı Uygulama",
    cmpNotable: "Öne Çıkan Kararlar",
    cmpSource: "Resmi Kaynak"
  },
  en: {
    brandSub: "Knowledge Hub",
    navAtlas: "Atlas", navGdpr: "GDPR", navCompare: "Compare", navCountries: "Countries", navPrinciples: "Principles", navAbout: "About",
    heroEyebrow: "KVKK · GDPR · EEA",
    heroTitle: "An <em>Atlas</em> of Data Privacy",
    heroLead: "From Türkiye to the European Union — the authorities, sanctions and landmark rulings that shape personal data protection, on a single globe. Pick a country to explore its framework.",
    heroCta: "Choose a country from the globe below",
    globeLabel: "— Atlas Mundi Privaticus —",
    globeLoading: "Loading the globe…",
    globeStat: "jurisdictions",
    gdprEyebrow: "Umbrella Framework",
    gdprTitle: "The General Data Protection <em>Regulation</em>",
    gdprDesc: "Effective 25 May 2018, Regulation (EU) 2016/679 applies directly across the EU's 27 member states and the 3 EEA countries. Accountability, data protection impact assessment, 72-hour breach notification and an adequacy-based transfer regime are its load-bearing pillars.",
    gdprLink: "Read the full text on EUR-Lex ↗",
    gdprStatYear: "in force",
    gdprStatCountries: "EU + EEA",
    gdprStatFine: "or 4% of turnover",
    gdprStatArticles: "articles",
    countriesTitle: "Browse the List",
    countriesSub: "Türkiye, the 27 EU member states and the 3 EEA countries — 31 jurisdictions in total",
    searchPlaceholder: "Search a country…",
    principlesEyebrow: "Pillars",
    principlesTitle: "Three Principles",
    principlesSub: "The three axes on which the KVKK and GDPR ecosystems converge — and diverge.",
    p1Title: "Data Subject Rights",
    p1Body: "Access, rectification, erasure, portability, objection and the right not to be subject to solely automated decisions. KVKK and GDPR overlap substantially; Germany, France and Spain layer in local rules on digital legacy and employee data.",
    p2Title: "Cross-Border Transfers",
    p2Body: "The GDPR ecosystem runs on adequacy decisions, Standard Contractual Clauses (SCCs) and Binding Corporate Rules (BCRs). Türkiye adopted a similar SCC regime with the March 2024 amendment; prior to that, Board authorisation was required.",
    p3Title: "Administrative Fines",
    p3Body: "The GDPR cap is 20 million EUR or 4% of worldwide turnover, whichever is higher. As of 1 January 2026 the highest single-head ceiling under KVKK is TRY 17.09 million (up from TRY 13.62 million in 2025). A single breach can attract multiple stacked sanctions.",
    footerHubTitle: "gdpr.com.tr Knowledge Hub",
    footerHubDesc: "An independent knowledge map for professionals working across KVKK and GDPR. Updated regularly from Board decisions, EDPB guidelines and national DPA developments.",
    footerDisclaimer: "Information on this site is general in nature and does not constitute legal advice. For specific matters, please consult qualified counsel.",
    footerResources: "Resources",
    footerContact: "Contact",
    footerLocation: "İstanbul, Türkiye",
    footerCopyright: "© 2026 gdpr.com.tr — all rights reserved.",
    footerTagline: "Independent knowledge hub · Not legal advice",
    pnlRegulator: "Supervisory Authority",
    pnlMaxFine: "Maximum Administrative Fine",
    pnlRights: "Data Subject Rights",
    pnlBases: "Lawful Bases",
    pnlExtraterritorial: "Extraterritorial Reach",
    pnlNotable: "Notable Enforcement",
    pnlSource: "Official Source",
    pnlYear: "In force",
    defGdprRights: ["Access","Rectification","Erasure (right to be forgotten)","Restriction","Portability","Object","Not be subject to automated decisions"],
    defGdprBases: ["Consent","Contract","Legal obligation","Vital interests","Public interest","Legitimate interests"],
    defGdprMaxFine: "EUR 20 million or 4% of global annual turnover, whichever is higher.",
    defGdprExtra: "Under Art. 3 GDPR, applies to controllers/processors targeting or monitoring individuals in the EU.",
    // Dashboard v2
    dashListTitle: "Countries",
    dashCompareTitle: "Compare",
    compareShowTable: "Show table",
    cardEmptyTitle: "Pick a country",
    cardEmptyBody: "Click any country on the globe or in the list. Supervisory authority, maximum fine and notable enforcement will appear here.",
    compareEmptyDash: "Pick at least two countries to see the comparison table.",
    filterAll: "All",
    filterGdpr: "GDPR",
    filterEea: "EEA",
    globeHint: "Drag · rotate · click a country",
    listEmpty: "No matches.",
    slotAdd: "Add country",
    compareEyebrow: "Side by Side",
    compareTitle: "Compare",
    compareSub: "Pick up to four countries to inspect the framework, supervisory authority, fines and enforcement record side by side.",
    compareEmpty: "Choose countries from the \"+ Add country\" boxes above to begin a comparison.",
    compareClear: "Clear all",
    compareHint: "Add one more country — the comparison table appears once you have two.",
    compareSlotEmpty: "Add country",
    pickerTitle: "Choose a country",
    pickerEmpty: "No matches.",
    pnlAddCompare: "Add to comparison",
    pnlAddedCompare: "Added to comparison",
    pnlFullCompare: "Comparison full (4)",
    cmpFramework: "Framework",
    cmpYear: "In force",
    cmpLawTitle: "Implementing law",
    cmpRegulator: "Supervisory authority",
    cmpMaxFine: "Maximum fine",
    cmpRights: "Data subject rights",
    cmpBases: "Lawful bases",
    cmpExtraterritorial: "Extraterritorial reach",
    cmpNotable: "Notable enforcement",
    cmpSource: "Official source"
  }
};

// ----- Country dataset -----
// iso_n3 = ISO 3166-1 numeric (used by world-atlas)
// rights/bases/maxFine/extraterritorial default to GDPR if framework starts with "GDPR"
window.COUNTRIES = [
  {
    code: "TR", iso_n3: "792", flag: "🇹🇷", lat: 39.0, lon: 35.0,
    framework: "KVKK", year: 2016, regulatorUrl: "https://www.kvkk.gov.tr",
    tr: {
      name: "Türkiye",
      lawTitle: "6698 Sayılı Kişisel Verilerin Korunması Kanunu",
      regulator: "Kişisel Verileri Koruma Kurumu (KVK Kurumu)",
      summary: "Türkiye'nin temel kişisel veri rejimi, GDPR'dan büyük ölçüde esinlenmekle birlikte VERBİS kaydı, açık rıza odaklı meşruiyet anlayışı ve yurt dışı aktarımdaki katı izin rejimiyle ayrışır. Mart 2024 değişiklikleriyle özel nitelikli verilerin işlenmesinde ek hukuki sebepler tanınmış ve yurt dışı aktarımda standart sözleşme rejimi getirilmiştir.",
      rights: ["Bilgi talep etme","Erişim","Düzeltme","Silme/yok etme","Aktarım bildirimini isteme","İtiraz","Zararın giderilmesini talep"],
      bases: ["Açık rıza","Kanunda açıkça öngörülmesi","Sözleşmenin kurulması/ifası","Hukuki yükümlülük","Aleniyet","Meşru menfaat","Hak tesisi/koruma"],
      maxFine: "17.092.242 TL (2026; her ihlal başına, yıllık yeniden değerlemeyle)",
      extraterritorial: "Türkiye'de yerleşik veri sahiplerini hedefleyen yurt dışı veri sorumlularını da kapsar.",
      notable: "Meta/WhatsApp (267 M TL, 2021), Amazon (1,2 M TL, 2020), Google reklam kimlikleri kararı (2023)."
    },
    en: {
      name: "Türkiye",
      lawTitle: "Law No. 6698 on the Protection of Personal Data",
      regulator: "Personal Data Protection Authority (KVK Kurumu)",
      summary: "Türkiye's flagship personal-data regime draws heavily on GDPR but diverges through the mandatory VERBİS register, a strongly consent-anchored notion of lawful basis, and historically a strict permit regime for international transfers. The March 2024 amendment added new lawful bases for sensitive data and introduced a Standard Contractual Clauses regime for cross-border transfers.",
      rights: ["Information","Access","Rectification","Erasure / destruction","Onward-transfer notification","Object","Compensation for damages"],
      bases: ["Explicit consent","Expressly provided by law","Necessity for a contract","Legal obligation","Publicly disclosed","Legitimate interests","Establishment/defence of legal rights"],
      maxFine: "TRY 17,092,242 (2026; per breach, re-valued annually)",
      extraterritorial: "Reaches non-Turkish controllers that target data subjects located in Türkiye.",
      notable: "Meta/WhatsApp (TRY 267M, 2021), Amazon (TRY 1.2M, 2020), Google advertising-ID decision (2023)."
    }
  },
  {
    code: "DE", iso_n3: "276", flag: "🇩🇪", lat: 51.0, lon: 10.4,
    framework: "GDPR", year: 2018, regulatorUrl: "https://www.bfdi.bund.de",
    tr: { name: "Almanya", lawTitle: "Bundesdatenschutzgesetz (BDSG)",
          regulator: "BfDI (federal) + 16 eyalet DPA'sı",
          summary: "Avrupa'nın en güçlü DPA ağına sahip ülke; özel sektörde 20+ kişi sürekli olarak veri işliyorsa zorunlu DPO atama yükümlülüğü gibi GDPR-üstü kurallar uygular. Çalışan verisi koruması (BDSG §26) özellikle katıdır.",
          notable: "1&1 Telecom 9,55 M EUR (2019), Vodafone 15 M EUR (2023), Notebooksbilliger.de 10,4 M EUR." },
    en: { name: "Germany", lawTitle: "Federal Data Protection Act (BDSG)",
          regulator: "BfDI (federal) + 16 state DPAs",
          summary: "Home to Europe's densest DPA network. Germany layers GDPR-plus rules on top of the regulation — including mandatory DPO appointment where 20+ persons routinely process personal data — and treats employee data (BDSG §26) with particular rigour.",
          notable: "1&1 Telecom EUR 9.55M (2019), Vodafone EUR 15M (2023), Notebooksbilliger.de EUR 10.4M." }
  },
  {
    code: "FR", iso_n3: "250", flag: "🇫🇷", lat: 46.6, lon: 2.2,
    framework: "GDPR", year: 2018, regulatorUrl: "https://www.cnil.fr",
    tr: { name: "Fransa", lawTitle: "Loi Informatique et Libertés (1978, revize 2018)",
          regulator: "CNIL — Commission Nationale de l'Informatique et des Libertés",
          summary: "Dünyanın en eski DPA'sına (1978) sahip Fransa, AB'nin en proaktif düzenleyicilerindendir. Çerez/izleme uygulamalarına yönelik 'Cookies and Trackers' rehberi (Md. 82 LIL) global ölçekte referanstır.",
          notable: "Google 150 M EUR (2022, çerez), Amazon 35 M EUR (2020), Clearview AI 20 M EUR (2022)." },
    en: { name: "France", lawTitle: "Loi Informatique et Libertés (1978, revised 2018)",
          regulator: "CNIL — Commission Nationale de l'Informatique et des Libertés",
          summary: "Home to the world's oldest DPA (1978), France is among the EU's most proactive regulators. The CNIL's 'Cookies and Trackers' guidance under Art. 82 LIL is a global reference point for online tracking compliance.",
          notable: "Google EUR 150M (2022, cookies), Amazon EUR 35M (2020), Clearview AI EUR 20M (2022)." }
  },
  {
    code: "IT", iso_n3: "380", flag: "🇮🇹", lat: 41.9, lon: 12.5,
    framework: "GDPR", year: 2018, regulatorUrl: "https://www.garanteprivacy.it",
    tr: { name: "İtalya", lawTitle: "Codice in materia di protezione dei dati personali",
          regulator: "Garante per la protezione dei dati personali",
          summary: "Garante, üretken yapay zekâ ve davranışsal reklam alanlarında AB içinde en agresif denetim kararları veren DPA'lardandır. ChatGPT'yi geçici olarak engelleyen ilk Avrupa otoritesidir (Mart 2023).",
          notable: "TIM 27,8 M EUR (2020), Enel Energia 26,5 M EUR (2022), OpenAI ChatGPT engellemesi (2023)." },
    en: { name: "Italy", lawTitle: "Personal Data Protection Code",
          regulator: "Garante per la protezione dei dati personali",
          summary: "The Garante is one of the EU's most assertive DPAs on generative AI and behavioural advertising. It became the first European regulator to temporarily block ChatGPT (March 2023).",
          notable: "TIM EUR 27.8M (2020), Enel Energia EUR 26.5M (2022), OpenAI ChatGPT block (2023)." }
  },
  {
    code: "ES", iso_n3: "724", flag: "🇪🇸", lat: 40.4, lon: -3.7,
    framework: "GDPR", year: 2018, regulatorUrl: "https://www.aepd.es",
    tr: { name: "İspanya", lawTitle: "LOPDGDD — Ley Orgánica 3/2018",
          regulator: "AEPD — Agencia Española de Protección de Datos",
          summary: "AB'de yıllık ceza sayısı bakımından en yüksek hacme sahip DPA'lardan biridir. Çocukların ve dijital iş gücü haklarının korunmasında öncü düzenlemeler getirmiştir.",
          notable: "CaixaBank 6 M EUR, Vodafone España (toplam 8+ M EUR), Google LLC 10 M EUR." },
    en: { name: "Spain", lawTitle: "LOPDGDD — Organic Law 3/2018",
          regulator: "AEPD — Spanish Data Protection Agency",
          summary: "One of the EU's highest-volume DPAs by annual penalty count. Spain has been a forerunner on children's rights and platform-worker data protection.",
          notable: "CaixaBank EUR 6M, Vodafone España (EUR 8M+ stacked), Google LLC EUR 10M." }
  },
  {
    code: "NL", iso_n3: "528", flag: "🇳🇱", lat: 52.1, lon: 5.3,
    framework: "GDPR", year: 2018, regulatorUrl: "https://autoriteitpersoonsgegevens.nl",
    tr: { name: "Hollanda", lawTitle: "Uitvoeringswet AVG (UAVG)",
          regulator: "Autoriteit Persoonsgegevens (AP)",
          summary: "AP, kamu sektörü algoritmik karar verme ve çocuk koruması konularında öne çıkan içtihatlara imza atmıştır. Toeslagenaffaire sonrası kamu kurumlarına ciddi yaptırımlar uygulanmıştır.",
          notable: "Belastingdienst 3,7 M EUR (2021), Uber 290 M EUR (2024), Booking.com 475 K EUR." },
    en: { name: "Netherlands", lawTitle: "GDPR Implementation Act (UAVG)",
          regulator: "Autoriteit Persoonsgegevens (AP)",
          summary: "The AP has produced influential case law on public-sector algorithmic decision-making and child protection. Following the Toeslagenaffaire scandal, public bodies have faced significant sanctions.",
          notable: "Belastingdienst EUR 3.7M (2021), Uber EUR 290M (2024), Booking.com EUR 475K." }
  },
  {
    code: "PL", iso_n3: "616", flag: "🇵🇱", lat: 51.9, lon: 19.1,
    framework: "GDPR", year: 2018, regulatorUrl: "https://uodo.gov.pl",
    tr: { name: "Polonya", lawTitle: "Ustawa o ochronie danych osobowych (2018)",
          regulator: "UODO — Urząd Ochrony Danych Osobowych",
          summary: "AB'de ilk büyük GDPR cezalarını veren DPA'lardan biridir. Kamu kayıt sistemlerindeki açık veri ihlallerine yönelik kararlarıyla öne çıkmıştır.",
          notable: "Bisnode 220 K EUR (2019), Morele.net 660 K EUR." },
    en: { name: "Poland", lawTitle: "Personal Data Protection Act 2018",
          regulator: "UODO — Personal Data Protection Office",
          summary: "Among the first DPAs in the EU to issue significant GDPR fines. Known for decisions on data leaks from public registers and large-scale scraping.",
          notable: "Bisnode EUR 220K (2019), Morele.net EUR 660K." }
  },
  {
    code: "BE", iso_n3: "056", flag: "🇧🇪", lat: 50.5, lon: 4.5,
    framework: "GDPR", year: 2018, regulatorUrl: "https://www.autoriteprotectiondonnees.be",
    tr: { name: "Belçika", lawTitle: "Loi de protection des données (30 juillet 2018)",
          regulator: "Autorité de protection des données (APD/GBA)",
          summary: "APD, AB içinde reklam teknolojisi (IAB Europe TCF) ve davranışsal reklam ekosistemine yönelik en önemli kararlardan birini vermiştir.",
          notable: "IAB Europe TCF kararı (2022), Proximus 100 K EUR." },
    en: { name: "Belgium", lawTitle: "Data Protection Act (30 July 2018)",
          regulator: "Data Protection Authority (APD/GBA)",
          summary: "The APD has issued one of the EU's most consequential decisions on the adtech ecosystem and behavioural advertising — IAB Europe's Transparency & Consent Framework.",
          notable: "IAB Europe TCF decision (2022), Proximus EUR 100K." }
  },
  {
    code: "SE", iso_n3: "752", flag: "🇸🇪", lat: 60.1, lon: 18.6,
    framework: "GDPR", year: 2018, regulatorUrl: "https://www.imy.se",
    tr: { name: "İsveç", lawTitle: "Dataskyddslagen (2018:218)",
          regulator: "Integritetsskyddsmyndigheten (IMY)",
          summary: "Schrems II sonrası ABD'ye veri transferlerinde en katı pozisyonu alan DPA'lardandır. Google Analytics kullanımı için yaptırım kararları vermiştir.",
          notable: "Klarna 7,5 M SEK, Tele2 12 M SEK, Spotify 5 M EUR (2023)." },
    en: { name: "Sweden", lawTitle: "Data Protection Act (2018:218)",
          regulator: "Integritetsskyddsmyndigheten (IMY)",
          summary: "One of the strictest DPAs on US data transfers post-Schrems II, IMY has issued binding decisions against Google Analytics deployments.",
          notable: "Klarna SEK 7.5M, Tele2 SEK 12M, Spotify EUR 5M (2023)." }
  },
  {
    code: "AT", iso_n3: "040", flag: "🇦🇹", lat: 47.5, lon: 14.6,
    framework: "GDPR", year: 2018, regulatorUrl: "https://www.dsb.gv.at",
    tr: { name: "Avusturya", lawTitle: "Datenschutzgesetz (DSG)",
          regulator: "Datenschutzbehörde (DSB)",
          summary: "DSB, NOYB örgütünün şikâyetleriyle hızlanan Google Analytics ve uluslararası aktarım davalarında AB içtihadını yönlendirmiştir.",
          notable: "Avusturya Posta İdaresi 9,5 M EUR (2019), Google Analytics kararı (2022)." },
    en: { name: "Austria", lawTitle: "Datenschutzgesetz (DSG)",
          regulator: "Datenschutzbehörde (DSB)",
          summary: "Acting on NOYB-led complaints, the DSB has steered EU case law on Google Analytics and international transfers.",
          notable: "Austrian Post EUR 9.5M (2019), Google Analytics decision (2022)." }
  },
  {
    code: "IE", iso_n3: "372", flag: "🇮🇪", lat: 53.4, lon: -8.2,
    framework: "GDPR", year: 2018, regulatorUrl: "https://www.dataprotection.ie",
    tr: { name: "İrlanda", lawTitle: "Data Protection Act 2018",
          regulator: "Data Protection Commission (DPC)",
          summary: "Meta, Google, X, TikTok, LinkedIn, Apple gibi büyük teknoloji şirketlerinin AB ana yerleşim yeri burası olduğundan, AB'deki en yüksek hacimli ve en büyük cezaları DPC vermektedir.",
          notable: "Meta 1,2 milyar EUR (2023, AB-ABD aktarımı), Instagram 405 M EUR, TikTok 345 M EUR." },
    en: { name: "Ireland", lawTitle: "Data Protection Act 2018",
          regulator: "Data Protection Commission (DPC)",
          summary: "With Meta, Google, X, TikTok, LinkedIn and Apple establishing their EU main-establishment in Ireland, the DPC issues both the highest-value and most numerous Big-Tech sanctions in the EU.",
          notable: "Meta EUR 1.2B (2023, EU–US transfers), Instagram EUR 405M, TikTok EUR 345M." }
  },
  {
    code: "PT", iso_n3: "620", flag: "🇵🇹", lat: 39.4, lon: -8.2,
    framework: "GDPR", year: 2019, regulatorUrl: "https://www.cnpd.pt",
    tr: { name: "Portekiz", lawTitle: "Lei 58/2019",
          regulator: "Comissão Nacional de Proteção de Dados (CNPD)",
          summary: "Kamu sağlık verileri ve çerez denetimleri konusunda aktiftir; ulusal nüfus sayımındaki Cloudflare/ABD aktarımına ilişkin önemli karar bu DPA'dandır.",
          notable: "INE (2021) nüfus sayımı durdurma kararı, hastane 400 K EUR." },
    en: { name: "Portugal", lawTitle: "Law 58/2019",
          regulator: "Comissão Nacional de Proteção de Dados (CNPD)",
          summary: "Active on public-sector health data and cookie audits. The CNPD's decision to halt the national census over Cloudflare/US transfers remains a touchstone.",
          notable: "Census halt against INE (2021), hospital EUR 400K." }
  },
  {
    code: "DK", iso_n3: "208", flag: "🇩🇰", lat: 56.2, lon: 9.5,
    framework: "GDPR", year: 2018, regulatorUrl: "https://www.datatilsynet.dk",
    tr: { name: "Danimarka", lawTitle: "Databeskyttelsesloven",
          regulator: "Datatilsynet",
          summary: "İhlal bildirimleri ve okul-öğrenci verilerinde Chromebook/Google Workspace kullanımına yönelik kararlarıyla AB içinde gündem oluşturmuştur.",
          notable: "Helsingør Belediyesi Chromebook kararı (2022), IDdesign 1,5 M DKK." },
    en: { name: "Denmark", lawTitle: "Data Protection Act",
          regulator: "Datatilsynet",
          summary: "Datatilsynet's decisions on breach notifications and Chromebook/Google Workspace use in schools have framed EU debate on US-cloud reliance in the public sector.",
          notable: "Helsingør Chromebook decision (2022), IDdesign DKK 1.5M." }
  },
  {
    code: "FI", iso_n3: "246", flag: "🇫🇮", lat: 64.0, lon: 26.0,
    framework: "GDPR", year: 2019, regulatorUrl: "https://tietosuoja.fi",
    tr: { name: "Finlandiya", lawTitle: "Tietosuojalaki (1050/2018)",
          regulator: "Tietosuojavaltuutetun toimisto",
          summary: "İş ilişkilerinde gizlilik ve sağlık verilerinin işlenmesi (Sote-sektörü) konusunda ayrıntılı rehberler yayımlamıştır.",
          notable: "Vastaamo psikoterapi ihlali ve sonrasında 608 K EUR ceza (2022)." },
    en: { name: "Finland", lawTitle: "Data Protection Act (1050/2018)",
          regulator: "Office of the Data Protection Ombudsman",
          summary: "Has published detailed guidance on workplace privacy and the processing of health-sector (Sote) data.",
          notable: "Vastaamo psychotherapy breach and subsequent EUR 608K fine (2022)." }
  },
  {
    code: "GR", iso_n3: "300", flag: "🇬🇷", lat: 39.0, lon: 22.0,
    framework: "GDPR", year: 2019, regulatorUrl: "https://www.dpa.gr",
    tr: { name: "Yunanistan", lawTitle: "Νόμος 4624/2019",
          regulator: "Hellenic Data Protection Authority (HDPA)",
          summary: "Telekom sektörü ve siyasi reklam segmentasyonu konusunda önemli kararlar vermiştir.",
          notable: "OTE/COSMOTE 9,25 M EUR (2022), Clearview AI 20 M EUR (2022)." },
    en: { name: "Greece", lawTitle: "Law 4624/2019",
          regulator: "Hellenic Data Protection Authority (HDPA)",
          summary: "Has issued significant decisions on the telecom sector and political-campaign micro-targeting.",
          notable: "OTE/COSMOTE EUR 9.25M (2022), Clearview AI EUR 20M (2022)." }
  },
  {
    code: "CZ", iso_n3: "203", flag: "🇨🇿", lat: 49.8, lon: 15.5,
    framework: "GDPR", year: 2019, regulatorUrl: "https://www.uoou.cz",
    tr: { name: "Çekya", lawTitle: "Zákon č. 110/2019 Sb.",
          regulator: "Úřad pro ochranu osobních údajů (ÚOOÚ)",
          summary: "Açık kaynak iletişim kayıtları (telekom log saklama) ve istihdam veri işleme alanlarında rehberlik üretir.",
          notable: "Avast tarayıcı uzantısı veri satışı soruşturması (2020)." },
    en: { name: "Czechia", lawTitle: "Act No. 110/2019 Coll.",
          regulator: "Úřad pro ochranu osobních údajů (ÚOOÚ)",
          summary: "Issues guidance on telecom metadata retention and employment-context processing.",
          notable: "Avast browser-extension data-sale investigation (2020)." }
  },
  {
    code: "HU", iso_n3: "348", flag: "🇭🇺", lat: 47.2, lon: 19.5,
    framework: "GDPR", year: 2018, regulatorUrl: "https://naih.hu",
    tr: { name: "Macaristan", lawTitle: "2011. évi CXII. törvény (Infotv.)",
          regulator: "NAIH — Nemzeti Adatvédelmi és Információszabadság Hatóság",
          summary: "Kamu denetimi, biyometri ve seçim kampanyaları döneminde gözetlenen reklam segmentlerine yönelik kararlarla bilinir.",
          notable: "Macar bankası 250 M HUF, DigiKabel ihlali yaptırımları." },
    en: { name: "Hungary", lawTitle: "Act CXII of 2011 (Infotv.)",
          regulator: "NAIH — National Authority for Data Protection",
          summary: "Known for decisions on public-sector surveillance, biometrics and election-period ad targeting.",
          notable: "Hungarian bank HUF 250M, DigiKabel breach sanctions." }
  },
  {
    code: "RO", iso_n3: "642", flag: "🇷🇴", lat: 45.9, lon: 25.0,
    framework: "GDPR", year: 2018, regulatorUrl: "https://www.dataprotection.ro",
    tr: { name: "Romanya", lawTitle: "Legea nr. 190/2018",
          regulator: "ANSPDCP",
          summary: "Bankacılık ihlalleri ve aydınlatma yükümlülüğü eksiklikleri üzerine düzenli yaptırım kararları yayımlar.",
          notable: "Unicredit Bank 130 K EUR, Vreau Credit kararı." },
    en: { name: "Romania", lawTitle: "Law No. 190/2018",
          regulator: "ANSPDCP",
          summary: "Regularly issues enforcement decisions over banking-sector breaches and transparency-notice shortcomings.",
          notable: "Unicredit Bank EUR 130K, Vreau Credit decision." }
  },
  {
    code: "BG", iso_n3: "100", flag: "🇧🇬", lat: 42.7, lon: 25.5,
    framework: "GDPR", year: 2019, regulatorUrl: "https://www.cpdp.bg",
    tr: { name: "Bulgaristan", lawTitle: "Закон за защита на личните данни",
          regulator: "CPDP",
          summary: "Kamu yönetimi ve maliye sistemlerine yönelik büyük çaplı veri sızıntısı kararıyla AB içinde dikkat çekmiştir.",
          notable: "Ulusal Gelir İdaresi (NRA) 2,6 M EUR (2019)." },
    en: { name: "Bulgaria", lawTitle: "Personal Data Protection Act",
          regulator: "CPDP",
          summary: "Issued one of the EU's largest public-sector breach fines following a leak from the national tax administration.",
          notable: "National Revenue Agency (NRA) EUR 2.6M (2019)." }
  },
  {
    code: "HR", iso_n3: "191", flag: "🇭🇷", lat: 45.1, lon: 15.2,
    framework: "GDPR", year: 2018, regulatorUrl: "https://azop.hr",
    tr: { name: "Hırvatistan", lawTitle: "Zakon o provedbi Opće uredbe o zaštiti podataka",
          regulator: "AZOP",
          summary: "AZOP'un kararları özellikle kamuya açık videoizleme (CCTV) sistemlerinde orantılılık ilkesini şekillendirir.",
          notable: "B2 Kapital 2,26 M EUR (2021)." },
    en: { name: "Croatia", lawTitle: "Act on Implementation of the GDPR",
          regulator: "AZOP",
          summary: "AZOP's decisions are particularly formative on the proportionality of public-space CCTV deployments.",
          notable: "B2 Kapital EUR 2.26M (2021)." }
  },
  {
    code: "SI", iso_n3: "705", flag: "🇸🇮", lat: 46.2, lon: 14.8,
    framework: "GDPR", year: 2023, regulatorUrl: "https://www.ip-rs.si",
    tr: { name: "Slovenya", lawTitle: "Zakon o varstvu osebnih podatkov (ZVOP-2, 2023)",
          regulator: "Informacijski pooblaščenec (IP-RS)",
          summary: "GDPR'a tam uyumlu yeni ulusal kanunu (ZVOP-2) 2023'te yürürlüğe giren son AB üyesi olmuştur.",
          notable: "Sağlık sektörü ve eğitim alanında çeşitli rehber kararları." },
    en: { name: "Slovenia", lawTitle: "Personal Data Protection Act (ZVOP-2, 2023)",
          regulator: "Informacijski pooblaščenec (IP-RS)",
          summary: "The last EU member state to align its implementing law (ZVOP-2) fully with GDPR — entered into force in 2023.",
          notable: "Guidance and decisions across the healthcare and education sectors." }
  },
  {
    code: "SK", iso_n3: "703", flag: "🇸🇰", lat: 48.7, lon: 19.7,
    framework: "GDPR", year: 2018, regulatorUrl: "https://dataprotection.gov.sk",
    tr: { name: "Slovakya", lawTitle: "Zákon č. 18/2018 Z. z.",
          regulator: "Úrad na ochranu osobných údajov SR",
          summary: "Çalışan izleme, biyometri ve dijital hizmetlerde aydınlatma kapsamı üzerine kararlar üretir.",
          notable: "Bankacılık kimlik doğrulama ve İK izleme kararları." },
    en: { name: "Slovakia", lawTitle: "Act No. 18/2018 Coll.",
          regulator: "Office for Personal Data Protection",
          summary: "Issues decisions on employee monitoring, biometrics and the scope of transparency notices in digital services.",
          notable: "Banking-KYC and HR-monitoring decisions." }
  },
  {
    code: "EE", iso_n3: "233", flag: "🇪🇪", lat: 58.6, lon: 25.0,
    framework: "GDPR", year: 2019, regulatorUrl: "https://www.aki.ee",
    tr: { name: "Estonya", lawTitle: "Isikuandmete kaitse seadus (IKS)",
          regulator: "Andmekaitse Inspektsioon (AKI)",
          summary: "AB'nin en dijital devletlerinden birinde, e-Estonya ekosistemi ve X-Road veri paylaşım altyapısı veri korumayı doğrudan etkiler.",
          notable: "e-Estonya kimlik kartı veri sızıntısı incelemeleri." },
    en: { name: "Estonia", lawTitle: "Personal Data Protection Act (IKS)",
          regulator: "Andmekaitse Inspektsioon (AKI)",
          summary: "In one of the EU's most digital states, the e-Estonia ecosystem and the X-Road data-exchange backbone shape data protection directly.",
          notable: "Investigations following the e-ID card disclosure incidents." }
  },
  {
    code: "LV", iso_n3: "428", flag: "🇱🇻", lat: 56.9, lon: 24.6,
    framework: "GDPR", year: 2018, regulatorUrl: "https://www.dvi.gov.lv",
    tr: { name: "Letonya", lawTitle: "Fizisko personu datu apstrādes likums",
          regulator: "Datu valsts inspekcija (DVI)",
          summary: "İhlal bildirimleri, doğrudan pazarlama ve çalışan e-posta izlemesi konularında rehberler yayımlar.",
          notable: "Yerel finans şirketlerine ve telekoma yönelik kararlar." },
    en: { name: "Latvia", lawTitle: "Personal Data Processing Law",
          regulator: "Datu valsts inspekcija (DVI)",
          summary: "Publishes guidance on breach notifications, direct marketing and employee email monitoring.",
          notable: "Decisions against local finance and telecom operators." }
  },
  {
    code: "LT", iso_n3: "440", flag: "🇱🇹", lat: 55.2, lon: 23.9,
    framework: "GDPR", year: 2018, regulatorUrl: "https://vdai.lrv.lt",
    tr: { name: "Litvanya", lawTitle: "Asmens duomenų teisinės apsaugos įstatymas",
          regulator: "VDAI",
          summary: "Doğrudan pazarlama, profil oluşturma ve kamu kurumu ihlalleri üzerine yaptırımlar uygulamıştır.",
          notable: "MisterTango 61 K EUR (2019), Vilnius Belediyesi kararı." },
    en: { name: "Lithuania", lawTitle: "Law on Legal Protection of Personal Data",
          regulator: "VDAI",
          summary: "Has sanctioned direct-marketing, profiling and public-sector breaches.",
          notable: "MisterTango EUR 61K (2019), Vilnius City decision." }
  },
  {
    code: "LU", iso_n3: "442", flag: "🇱🇺", lat: 49.6, lon: 6.1,
    framework: "GDPR", year: 2018, regulatorUrl: "https://cnpd.public.lu",
    tr: { name: "Lüksemburg", lawTitle: "Loi du 1er août 2018",
          regulator: "CNPD",
          summary: "Amazon AB ana yerleşim yeri olduğundan, AB'deki en büyük tek GDPR cezasını veren DPA olmuştur (746 M EUR, 2021).",
          notable: "Amazon 746 M EUR (2021)." },
    en: { name: "Luxembourg", lawTitle: "Act of 1 August 2018",
          regulator: "CNPD",
          summary: "Because Amazon's EU main-establishment sits here, the CNPD has issued the single largest GDPR fine to date (EUR 746M, 2021).",
          notable: "Amazon EUR 746M (2021)." }
  },
  {
    code: "MT", iso_n3: "470", flag: "🇲🇹", lat: 35.9, lon: 14.4,
    framework: "GDPR", year: 2018, regulatorUrl: "https://idpc.org.mt",
    tr: { name: "Malta", lawTitle: "Data Protection Act (Chapter 586)",
          regulator: "IDPC",
          summary: "Küçük ölçekli ama oyun (iGaming) ve finans sektörü yoğun olduğu için bu alanlarda spesifik rehberlik üretir.",
          notable: "Vatandaşlık programı (Lands Authority) veri ifşası kararı." },
    en: { name: "Malta", lawTitle: "Data Protection Act (Chapter 586)",
          regulator: "IDPC",
          summary: "Small in scale but sector-rich — the IDPC publishes targeted guidance for iGaming and finance.",
          notable: "Lands Authority disclosure decision." }
  },
  {
    code: "CY", iso_n3: "196", flag: "🇨🇾", lat: 35.1, lon: 33.4,
    framework: "GDPR", year: 2018, regulatorUrl: "https://www.dataprotection.gov.cy",
    tr: { name: "Kıbrıs", lawTitle: "Law 125(I)/2018",
          regulator: "Office of the Commissioner for Personal Data Protection",
          summary: "Finansal hizmetler ve denizcilik şirketleri üzerinde uluslararası veri akışı denetimi yoğundur.",
          notable: "Telekom sektörüne yönelik kararlar." },
    en: { name: "Cyprus", lawTitle: "Law 125(I)/2018",
          regulator: "Office of the Commissioner for Personal Data Protection",
          summary: "International data-flow oversight is intense given the country's large financial-services and maritime sectors.",
          notable: "Decisions against telecom operators." }
  },
  {
    code: "IS", iso_n3: "352", flag: "🇮🇸", lat: 64.9, lon: -19.0,
    framework: "GDPR (EEA)", year: 2018, regulatorUrl: "https://www.personuvernd.is",
    tr: { name: "İzlanda", lawTitle: "Lög um persónuvernd (90/2018)",
          regulator: "Persónuvernd",
          summary: "AB üyesi olmamakla birlikte EEA Anlaşması üzerinden GDPR'ı uygular. Sağlık veri tabanı projeleri (deCODE) dahil hassas alanlarda denetimi yoğundur.",
          notable: "Sağlık verisi ve sosyal medya denetimleri." },
    en: { name: "Iceland", lawTitle: "Act on Data Protection (90/2018)",
          regulator: "Persónuvernd",
          summary: "Although not an EU member, Iceland applies the GDPR via the EEA Agreement. Health-database projects (incl. deCODE) keep enforcement scrutiny high.",
          notable: "Health-data and social-media supervision cases." }
  },
  {
    code: "LI", iso_n3: "438", flag: "🇱🇮", lat: 47.2, lon: 9.6,
    framework: "GDPR (EEA)", year: 2019, regulatorUrl: "https://www.datenschutzstelle.li",
    tr: { name: "Lihtenştayn", lawTitle: "Datenschutzgesetz (LR 235.1)",
          regulator: "Datenschutzstelle (DSS)",
          summary: "EEA üyesi olduğundan GDPR'ı doğrudan uygular. Finansal varlık yönetiminin yoğun olduğu ülkede CRS/FATCA bağlamında veri aktarımları öne çıkar.",
          notable: "Banka müşteri verisi denetimleri." },
    en: { name: "Liechtenstein", lawTitle: "Datenschutzgesetz (LR 235.1)",
          regulator: "Datenschutzstelle (DSS)",
          summary: "As an EEA member, Liechtenstein applies the GDPR directly. Wealth-management exposure makes CRS/FATCA-related transfers a focal point.",
          notable: "Bank customer-data supervision cases." }
  },
  {
    code: "NO", iso_n3: "578", flag: "🇳🇴", lat: 60.5, lon: 8.5,
    framework: "GDPR (EEA)", year: 2018, regulatorUrl: "https://www.datatilsynet.no",
    tr: { name: "Norveç", lawTitle: "Personopplysningsloven (15. juni 2018)",
          regulator: "Datatilsynet",
          summary: "EEA üyesi olarak GDPR'ı uygular. Davranışsal reklam (Grindr, Meta) ve sosyal yardım algoritmaları üzerine güçlü içtihat üretmiştir.",
          notable: "Grindr 65 M NOK (2021), Meta günlük 1 M NOK zorlama cezası (2023)." },
    en: { name: "Norway", lawTitle: "Personal Data Act (15 June 2018)",
          regulator: "Datatilsynet",
          summary: "Applies the GDPR via the EEA. Datatilsynet has produced influential rulings on behavioural advertising (Grindr, Meta) and social-welfare algorithms.",
          notable: "Grindr NOK 65M (2021), Meta NOK 1M daily compulsion fine (2023)." }
  }
];

// Resolve a country record into a flat localized view (defaults to GDPR fields when missing).
window.resolveCountry = function(c, lang) {
  const I = window.I18N[lang];
  const loc = c[lang] || {};
  const isGdpr = c.framework.startsWith("GDPR");
  return {
    code: c.code,
    iso_n3: c.iso_n3,
    flag: c.flag,
    lat: c.lat,
    lon: c.lon,
    framework: c.framework,
    year: c.year,
    regulatorUrl: c.regulatorUrl,
    name: loc.name,
    lawTitle: loc.lawTitle,
    regulator: loc.regulator,
    summary: loc.summary,
    notable: loc.notable,
    rights: loc.rights || (isGdpr ? I.defGdprRights : []),
    bases: loc.bases || (isGdpr ? I.defGdprBases : []),
    maxFine: loc.maxFine || (isGdpr ? I.defGdprMaxFine : ""),
    extraterritorial: loc.extraterritorial || (isGdpr ? I.defGdprExtra : "")
  };
};
